---
title: 解读 10 条好的学习习惯
author: Jared
date: '2018-03-05'
slug: '10'
categories:
  - Machine learning
  - deep learning
tags:
  - learn
---

https://www.coursera.org/learn/learning-how-to-learn/resources/TDXlD

## Intro to 10 Rules of Studying

Cousera 课程 learn how to learn! 

本课程将介绍各领域专家所使用的学习方法，他们包括艺术家、文学家、数学家、科学家、运动员和很多其他领域专家。我们将学习如何使用两种不同的大脑模式，以及大脑如何封装（“chunks”）信息。我们还将介绍能力错觉（illusions of learning），记忆技巧，对付拖延症的方法，以及研究表明能帮助我们掌握困难科目的方法。

无论您在所学领域是专家还是菜鸟，您都可以使用这些方法，改变自己的思维模式，重塑自己的人生。如果您是所学领域的专家，通过学习大脑认知的底层知识，您可以进一步提高自己的学习能力，您将了解反直觉的考试技巧和见解，从而能够更高效地完成作业和习题。如果您在学习中遇到困难，系统有效的学习技巧将帮助您将走上正轨。无论您希望学习什么内容，这门课程都可以作为您的指南。

> 该课程提供了10条我们必须理解和使用的学习方法。


## 主要内容

- **Use recall.** 

After you read a page, look away and recall the main ideas. Highlight very little, and never highlight anything you haven’t put in your mind first by recalling. Try recalling main ideas when you are walking to class or in a different room from where you originally learned it. An ability to recall—to generate the ideas from inside yourself—is one of the key indicators of good learning.

通过理解所学内容，从自己的大脑中构建所学内容的逻辑结构是极其重要的事情。所以，为了防止自己欺骗自己，不要做太多的笔记。使用专注模式通过回想构建所学知识对应的神经连接，为了使得神经连接更强，构建的时候加入一些变化，比如回想地点的变化，时间的变化。

- **Test yourself**, on everything, all the time. Flash cards are you friend.

自己选择一个合适的问题问自己很重要，比如如何从头开始建立一个线性回归的梯度下降法估计参数？

- Chunk your problems. Chunking is understanding and practicing with a problem solution so that it can all come to mind in a flash. After you solve a problem, rehaearse it, make sure you can solve it cold-every step. Pretend it's song and learn to play it over and over again in your mind, so the information combines into one smooth chunk you can pull up whenever you want.

例如，使用 pytorch 实现梯度下降法 求函数 $$J(w) = ((wx)^2 + 1)^2, x = 1$$ 的最小值。解决这个数学问题的整个过程就是一个 chunk, 需要不停的回顾和训练。

